In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
x = np.zeros(10,dtype = int)
x[4] = 1
print(x)

[0 0 0 0 1 0 0 0 0 0]


In [3]:
#2. Create a vector with values ranging from 10 to 49.
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
z = np.arange(0,9).reshape(3,3)
print(z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
n = np.array([1,2,0,0,4,0])
print("originalarray",n)
result = np.nonzero(n == 0)
print(result)

originalarray [1 2 0 0 4 0]
(array([2, 3, 5], dtype=int64),)


In [11]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
n = np.random.random(10)
print("Original array",n)
print("The minimum value of array", n.min())
print("The max value of array", n.max())

Original array [0.29970432 0.51225385 0.35612924 0.38504345 0.5725156  0.74476676
 0.80587244 0.66762087 0.11916177 0.50762185]
The minimum value of array 0.11916176816767066
The max value of array 0.8058724384355663


In [12]:
#6. Create a random vector of size 30 and find the mean value.
z = np.random.random(30)
y = z.mean()
print(y)

0.40930848305439854
